"""Add order details and order items

Revision ID: 3b70a04207ed
Revises: 8cd6f58a1484
Create Date: 2025-03-20 13:57:02.453762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b70a04207ed'
down_revision: Union[str, None] = '8cd6f58a1484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.add_column('orders', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('email', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_postal_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'comment')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'delivery_postal_code')
    op.drop_column('orders', 'delivery_city')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'delivery_method')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'email')
    op.drop_column('orders', 'customer_name')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    # ### end Alembic commands ###
